CREATE TABLE PAISES(
    ID_PAISES NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(50) NOT NULL
);
CREATE TABLE ESTADOS(
    ID_ESTADOS NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ID_PAIS NUMBER NOT NULL,
    FOREIGN KEY(ID_PAIS)
        REFERENCES PAISES( ID_PAISES )
        ON DELETE CASCADE
);
CREATE TABLE CIDADES(
    ID_CIDADES NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ID_ESTADO NUMBER NOT NULL,
    FOREIGN KEY(ID_ESTADO)
        REFERENCES ESTADOS( ID_ESTADOS )
        ON DELETE CASCADE
);
CREATE TABLE BANCOS(
    ID_BANCOS NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL
);
CREATE TABLE AGENCIAS(
    ID_AGENCIAS NUMBER NOT NULL PRIMARY KEY,
    NOME VARCHAR2(100) NOT NULL,
    ID_BANCO NUMBER NOT NULL,
    ID_CIDADE NUMBER NOT NULL,
    FOREIGN KEY(ID_BANCO) 
        REFERENCES BANCOS( ID_BANCOS ) 
        ON DELETE CASCADE,
    FOREIGN KEY(ID_CIDADE) 
        REFERENCES CIDADES( ID_CIDADES ) 
        ON DELETE CASCADE
);
CREATE TABLE TIPO_CONTA(
    ID_TIPO_CONTA NUMBER NOT NULL PRIMARY KEY,
    DESCRICAO VARCHAR2(10) CHECK( DESCRICAO IN ('PJ','PF','CONJ','INVEST') )
);
CREATE TABLE CONTAS(
    ID_CONTAS NUMBER NOT NULL PRIMARY KEY,
    ID_TIPO_CONTA NUMBER NOT NULL,
    ID_AGENCIA NUMBER NOT NULL,
    NUMERO NUMBER NOT NULL,
    SALDO DECIMAL NOT NULL,
    FOREIGN KEY(ID_TIPO_CONTA) 
        REFERENCES TIPO_CONTA( ID_TIPO_CONTA ) 
        ON DELETE CASCADE,
    FOREIGN KEY(ID_AGENCIA) 
        REFERENCES AGENCIAS( ID_AGENCIAS ) 
        ON DELETE CASCADE
);
CREATE TABLE CLIENTES(
    ID_CLIENTES NUMBER NOT NULL PRIMARY KEY,
    CPF CHAR(14) NOT NULL,
    NOME VARCHAR2(100) NOT NULL
);
CREATE TABLE MOVIMENTACAO(
    ID_MOVIMENTACAO NUMBER NOT NULL PRIMARY KEY,
    VALOR DECIMAL NOT NULL,
    TIPO VARCHAR2(7) CHECK( TIPO IN ('DEBITO','CREDITO') ),
    ID_CONTA NUMBER NOT NULL,
    FOREIGN KEY(ID_CONTA)
        REFERENCES CONTAS(ID_CONTAS)
        ON DELETE CASCADE
);
CREATE TABLE CIDADES_X_CLIENTES(
    ID_CLIENTE INTEGER NOT NULL,
    ID_CIDADE INTEGER NOT NULL,
    CONSTRAINT ID_CIDADE_CLIENTE PRIMARY KEY(ID_CLIENTE, ID_CIDADE),
    FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTES)
        ON DELETE CASCADE,
    FOREIGN KEY(ID_CIDADE)
        REFERENCES CIDADES(ID_CIDADES)
        ON DELETE CASCADE
);
CREATE TABLE CONTAS_X_CLIENTES(
    ID_CLIENTE INTEGER NOT NULL,
    ID_CONTA INTEGER NOT NULL,
    CONSTRAINT ID_CONTA_CLIENTE PRIMARY KEY(ID_CLIENTE, ID_CONTA),
    FOREIGN KEY(ID_CLIENTE)
        REFERENCES CLIENTES(ID_CLIENTES)
        ON DELETE CASCADE,
    FOREIGN KEY(ID_CONTA)
        REFERENCES CONTAS(ID_CONTAS)
        ON DELETE CASCADE
);